### PR TITLE
Rebuild for as suggested

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
Hi @NingWang1990, 

it is recommended to follow the steps suggested from conda to maintain compatibility to the rest of the build system. All we have to do is add the comment: `@conda-forge-admin, please rerender` this automatically triggers the update. 

Best, 

Jan

**Comment by NingWang1990** [comment]
Hi, Jan,
I see. Thanks a lot! It was my first time to update pystem in conda forge. I simply changed the version in meta.yaml to 0.0.22 in my pull request. Was it not the correct way to update pystem in conda forge? 

Best regards,
Ning

Best regards,
Ning

**Comment by jan-janssen** [comment]
That is all fine, it is just a quick reminder.

**Pull request merged**
